apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
    servicetier: dev

spec: 
  template:
    metadata: 
      name: myapp-rc
      labels:
        app: myapp-rc
        servicetier: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
  
  replicas: 3

